### ISSUE TITLE
[question] need add Calls in loop

### ISSUE THREAD

**Issue by growupinv** [depocket/multicall-go#6]
can we add Calls in loop?

```
        //len(listAdresses)=5
	//after loop  ,len(caller.Calls) always 1
	for _, tokenList := range listAdresses {
		caller = NewContractBuilder().
			WithChainConfig(DefaultChainConfigs[tokenList.Chain]).
			AddMethod("function balanceOf(address)(uint256)").
			AddCall("ts", tokenList.Adress, "balanceOf", common.HexToAddress("0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8"))
	}
```

if directly add method - `AddCall("ts", tokenList.Adress, "balanceOf", common.HexToAddress("0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8"))`
then len(caller.Calls) increase,
or how properly add cals in loop?

**Comment by himitsuko** [comment]
@growupinv 
You can simple to add more call like this

```
caller = NewContractBuilder().
			WithChainConfig(DefaultChainConfigs[tokenList.Chain]).
			AddMethod("function balanceOf(address)(uint256)")
	for _, tokenList := range listAdresses {
		caller.AddCall(fmt.Sprintf("ts-%s",tokenList.Address.String()), tokenList.Adress, "balanceOf", common.HexToAddress("0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8"))
	}
```

We mapped the call data and the call to a map
The key for the map is the first argument in AddCall function.
Please ensure that the key is unique when you add a call.

**Comment by growupinv** [comment]
> fmt.Sprintf("ts-%s"...
oh, this is the key to the solution,so simple
everything works well

**Comment by growupinv** [comment]
Thanks again=)
