### ISSUE TITLE
[Question] call from contract (not a function)

### ISSUE THREAD

**Issue by growupinv** [depocket/multicall-go#7]
Hey,
i tried today to call the contract and call the variable tokensList.call();

but then I realized that the parser parses only functions, is it possible to call a variable?
for example :
https://docs.fantom.foundation/fantom-finance/fmint/token-registry#reading-list-of-known-tokens

**Comment by himitsuko** [comment]
I haven't even try anythings like that, did you try to call the variable same as below?

```
var tRegistryAddress = "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23";
call := NewContractBuilder().WithChainConfig(...).AddMethod("tokenList(uint256)(address)")
...
call.Call('smth', tRegistryAddress, "tokensList", 0)
```

**Comment by growupinv** [comment]
> I haven't even try anythings like that, did you try to call the variable same as below?
> 
> ```
> var tRegistryAddress = "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23";
> call := NewContractBuilder().WithChainConfig(...).AddMethod("tokenList(uint256)(address)")
> ...
> call.Call('smth', tRegistryAddress, "tokensList", 0)
> ```

i try , get error
panic: method 'tokensList' not found

**Comment by growupinv** [comment]
contract adress :
https://github.com/Fantom-foundation/Fantom-FMint/blob/master/contracts/utility/FantomMintTokenRegistry.sol

need tokensList call

**Comment by himitsuko** [comment]
@growupinv 
Did you test this way?
```
caller := NewContractBuilder().
		WithChainConfig(DefaultChainConfigs["fantom"]).
		AddMethod("tokensList(uint256)(address)")
	_, result, err := caller.
		AddCall("tl", "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23", "tokensList", big.NewInt(0)).
		Call(nil)
	if err != nil {
		log.Fatalf( "Error calling %s contract", "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23")
	} else {
		fmt.Printf("Result: %v\n", result)
	}
```

I tested it, and it work

**Comment by growupinv** [comment]
> caller := NewContractBuilder().
> 		WithChainConfig(DefaultChainConfigs["fantom"]).
> 		AddMethod("tokensList(uint256)(address)")
> 	_, result, err := caller.
> 		AddCall("tl", "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23", "tokensList", big.NewInt(0)).
> 		Call(nil)

i get panic: interface conversion: interface {} is common.Address, not *big.Int

**Comment by himitsuko** [comment]
I think your
>i get panic: interface conversion: interface {} is common.Address, not *big.Int

error come from the `result` casting statement right?
for example
```
caller := NewContractBuilder().
		WithChainConfig(DefaultChainConfigs["fantom"]).
		AddMethod("tokensList(uint256)(address)")
	_, result, err := caller.
		AddCall("tl", "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23", "tokensList", big.NewInt(0)).
		Call(nil)
	if err != nil {
		log.Fatalf("Error calling %s contract", "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23")
	} else {
		value := result["tl"][0].(*big.Int)
		fmt.Printf("Result: %v\n", value)
	}
```

`value := result["tl"][0].(*big.Int)` in the code will throw `panic: interface conversion: interface {} is common.Address, not *big.Int`

---

If you like reproduce this example https://docs.fantom.foundation/fantom-finance/fmint/token-registry#reading-list-of-known-tokens, below is an example in golang

```
caller := NewContractBuilder().
		WithChainConfig(DefaultChainConfigs["fantom"]).
		AddMethod("tokensList(uint256)(address)")
	_, result, err := caller.
		AddCall("tl", "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23", "tokensList", big.NewInt(0)).
		Call(nil)
	if err != nil {
		log.Fatalf("Error calling %s contract", "0x5ac50e414bb625ce7dc17ad165a604bf3ca8fd23")
	} else {
		tokenAddress := result["tl"][0].(common.Address)
		fmt.Printf("%s", tokenAddress.String())
	}
```

**Comment by growupinv** [comment]
yep, your code works =), 
but they wrote that type of variable tokenList is address[], 
i try change this 

`AddMethod("tokensList(address)(address[])")
`
but panic again(
need to add some other args?

for their docs expected to receive a list of contract tokens

**Comment by himitsuko** [comment]
Please confirm the docs carefully!
Only one token's address was return in this example:
https://docs.fantom.foundation/fantom-finance/fmint/token-registry#reading-list-of-known-tokens

And `tokensList(address)([]list)` isn't a right define. You can confirm on ABI section at there: https://ftmscan.com/address/0x971010d151a110469644ef212ecc9aa311a4af26#code:~:text=Submit%20Audit%20Here-,Contract%20ABI,-Export%20ABI


If you need to get the token list, please try to query the `tokensCount`. After that `AddCall(...)` in a loop from 0 to `tokensCount-1` and call in batch with `.Call(nil)`

`tokensCount`: please read the docs below
https://docs.fantom.foundation/fantom-finance/fmint/token-registry#reading-list-of-known-tokens

**Comment by growupinv** [comment]
> https://ftmscan.com/address/0x971010d151a110469644ef212ecc9aa311a4af26#code:~:text=Submit%20Audit%20Here-,Contract%20ABI,-Export%20ABI

you right, im use sol instead of abi, do not judge strictly)
I will keep trying)

**Comment by himitsuko** [comment]
@growupinv 
Oh, sorry about that but it is impossible to get the full variable value in your case.
