### ISSUE TITLE
[question] our contract Multicall2 or Multicall1?

### ISSUE THREAD

**Issue by growupinv** [depocket/multicall-go#8]
**hey,** i read this, and create this question

_try aggregate
By default if you dont turn tryAggregate to true if 1 eth_call fails in your multicall the whole result will throw. If you turn tryAggregate to true it means if 1 of your eth_call methods fail it still return you the rest of the results. It will still be in the same order as you expect but you have a success boolean to check if it passed or failed. Keep in mind that if using a custom multicall contract deployment, Multicall version 1's will not work. Use a Multicall2 deployment (contract can be found [here]_(https://github.com/makerdao/multicall/blob/master/src/Multicall2.sol)).

and do you do the deployment yourself or just take the addresses of the contracts from the public?

as I understand it, there are a lot of these contracts and there are many already deployed, 
do you need deployed addresses of contracts in other networks (I could search and drop them here) or do you have it all and add it?

**Comment by growupinv** [comment]
and how u guys get prices in usd, are you referring to a contract or third party api?

**Comment by himitsuko** [comment]
For the issue description
 - We now supported to call the MulticallV2 by https://github.com/depocket/multicall-go/pull/9 on v0.0.31

For this comment https://github.com/depocket/multicall-go/issues/8#issuecomment-1162744414
 - Apart of them come from the third party API

**Comment by growupinv** [comment]
Cool, thx for answer
